### ISSUE TITLE
Wdrożenie: PUT /sale/offers/{offerID}

### ISSUE THREAD

**Issue by jacekmichalski** [PiotrFerenc/Allegro-api-rest-client#1]
Witam,
świetny rest client, jestem pod wrażeniem :-)

Czy istnieją plany aby wdrożyć oprócz queries również commands, np.

PUT /sale/offers/{offerID}

Niestety nie mam dużego doświadczenia w CQRS i MediatR, jednak mając ściągę chętnie pomogę
Pozdrawiam,
Jacek Michalski

**Comment by PiotrFerenc** [comment]
Witam,
tak są takie plany. Może nawet w tym tygodniu się uda 💪

**Comment by jacekmichalski** [comment]
Genialnie! :-) Nie mogę się doczekać!

Trzymam kciuki! 👍

**Comment by PiotrFerenc** [comment]
Mamy aktualizację oferty! 💪
